# Lines configured by zsh-newuser-install
# Shell history path
HISTFILE="${HOME}/.cache/zsh/.histfile"

# Basic auto/tab complete:
autoload -Uz compinit                #marks compinit as a function, not external program
zstyle ':completion:*' menu select
zmodload zsh/complist

#allow tab completion in the middle of a word
setopt COMPLETE_IN_WORD

#redefines the foleder where the command suggestions are stored
compinit -d "${HOME}/.cache/zsh/zcompdump-${ZSH_VERSION}"
_comp_options+=(globdots)		# Include hidden files.

setopt extendedglob nomatch

unsetopt autocd beep

# browse history with the up and down keys
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# VI MODE SETTINGS
# enables vi mode
bindkey -v
export KEYTIMEOUT=1

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
# bindkey -v '^?' backward-delete-char

#disables flow control for vim mapping
stty -ixon

# Change cursor shape for different vi modes.
zle-keymap-select () {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename "${HOME}/.zshrc"

compinit

#----------------------#
# User-defined Options #
#----------------------#
#sourcing customized terminal colorsfor more informations look at 
#https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
#Shakiba Moshiri's answer
if [[ -e .termocolors ]]; then
  source .termcolors
fi

# maximazes the size of the allowed core dump
ulimit -c unlimited

# Load shortcuts if the file exists and TMUX is not set
if
[[ -f "${HOME}/.config/terminal/shortcutrc" ]] && [[ -z "${TMUX}" ]]; then
source "${HOME}/.config/terminal/shortcutrc"
fi
[[ -f "${HOME}/.config/terminal/aliasrc" ]] && source "${HOME}/.config/terminal/aliasrc"
[[ -f "${HOME}/.config/terminal/functionsrc" ]] && source "${HOME}/.config/terminal/functionsrc"


# PLUGINS
# setting up custom plugins
# zsh-history-search
source "${HOME}/.config/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh"
# zsh-syntax-highlighting
source "${HOME}/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
# zsh-autosuggestions
source "${HOME}/.config/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
# zsh-vi-mode - Enhancement for zsh 
# source "${HOME}/.config/zsh/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh"
# zsh-z 
source "${HOME}/.config/zsh/plugins/zsh-z/zsh-z.plugin.zsh"


# PROMPT
# Loading Starship settings
eval "$(starship init zsh)"
# source "${HOME}/.config/zsh/powerline_setup.sh"
