# Lines configured by zsh-newuser-install
HISTFILE=~/.cache/zsh/.histfile

# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist

#redefines the foleder where the command suggestions are stored
compinit -d $HOME/.cache/zsh/zcompdump-$ZSH_VERSION
_comp_options+=(globdots)		# Include hidden files.

setopt appendhistory extendedglob nomatch
unsetopt autocd beep

# browse history with the up and down keys
bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

bindkey -v
export KEYTIMEOUT=1

# vi mode
# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char

# Change cursor shape for different vi modes.
function zle-keymap-select {
  if [[ ${KEYMAP} == vicmd ]] ||
     [[ $1 = 'block' ]]; then
    echo -ne '\e[1 q'
  elif [[ ${KEYMAP} == main ]] ||
       [[ ${KEYMAP} == viins ]] ||
       [[ ${KEYMAP} = '' ]] ||
       [[ $1 = 'beam' ]]; then
    echo -ne '\e[5 q'
  fi
}

# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/paolobaldan/.zshrc'

autoload -Uz compinit
compinit

#----------------------#
# User-defined Options #
#----------------------#
#sourcing customized terminal colorsfor more informations look at 
#https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
#Shakiba Moshiri's answer
if [[ -e .termocolors ]]; then
  source .termcolors
fi

#disables flow control for vim mapping
stty -ixon

# Load shortcuts if the file exists and TMUX is not set
if
[[ -f "$HOME/.config/zsh/shortcutrc" ]] && [[ -z "$TMUX" ]]; then
source "$HOME/.config/zsh/shortcutrc"
fi
[[ -f "$HOME/.config/zsh/aliasrc" ]] && source "$HOME/.config/zsh/aliasrc"
[[ -f "$HOME/.config/zsh/functionsrc" ]] && source "$HOME/.config/zsh/functionsrc"


# prompt configuration
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
source ~/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Sourcing Powerline
# export PATH=$PATH:/Users/paolobaldan/Library/Python/3.9/bin
# powerline-daemon -q
# . /Users/paolobaldan/Library/Python/3.9/lib/python/site-packages/powerline/bindings/zsh/powerline.zsh

# setting up custom plugins
# zsh-history-search
source "$HOME/.config/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh"
# zsh-syntax-highlighting
source "$HOME/.config/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
# zsh-autosuggestions
source "$HOME/.config/zsh/plugins/zsh-autosuggestions-master/zsh-autosuggestions-master.zsh"
