CompileFlags: # Tweak the parse settings
  Add: [
      # Compiler flags
      "-xc++",
      "-std=c++17",
      "-Wall",
      "-Wextra", # reasonable and standard
      "-Wshadow", # warn the user if a variable declaration shadows one from a parent context
      "-Wnon-virtual-dtor", # warn the user if a class with virtual functions has a non-virtual destructor. This helps
                            #, catch hard to track down memory errors
      "-Wold-style-cast", # warn for c-style casts
      "-Wcast-align", # warn for potential performance problem casts
      "-Wunused", # warn on anything being unused
      "-Woverloaded-virtual", # warn if you overload (not override) a virtual function
      "-Wpedantic", # warn if non-standard C++ is used
      "-Wconversion", # warn on type conversions that may lose data
      "-Wsign-conversion", # warn on sign conversions
      "-Wnull-dereference", # warn if a null dereference is detected
      "-Wdouble-promotion", # warn if float is implicit promoted to double
      "-Wformat=2", # warn on security issues around functions that format output (ie printf)
    ]
    # Compiler: clang++

Index:
  Background: Build # Build a type + incoming reference index in the background

Diagnostics:
  # UnusedIncludes: Strict
  # https://clang.llvm.org/extra/clang-tidy/
  ClangTidy:
    Add: '*'
    Remove: [
      'fuchsia-*',
      'google-*',
      'zircon-*',
      'abseil-*',
      'modernize-*',
      'llvm*',
    ]

# InlayHints:
#   Enabled: Yes
#   ParameterNames: Yes
#   DeducedTypes: Yes
